'use strict';
(()=>{
 const $=id=>document.getElementById(id),base='https://oda-pagos.oda-pagos-cloudflare.workers.dev';let token='',generation=0;
 const say=s=>{$('message').textContent=s};
 async function api(path,body){const r=await fetch(base+'/api/admin/'+path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'No se pudo completar la operación.');return d;}
 const el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n};
 const testSection=el('section');testSection.append(el('h2','Compra de prueba en Mercado Pago'),el('p','Usa el correo de tu comprador de prueba. Se reservará un corazón pintado del inventario para este pedido de prueba, sin envío. No uses tarjetas reales. Tras comprobar el resultado, el estudio deberá revisar y reponer esa unidad en el inventario.'));
 const testForm=el('form'),testLabel=el('label','Correo del comprador de prueba'),testEmail=el('input'),testButton=el('button','Crear pedido de prueba'),testResult=el('div');testEmail.type='email';testEmail.required=true;testLabel.append(testEmail);testForm.append(testLabel,testButton);testSection.append(testForm,testResult);$('panel').prepend(testSection);let testKey='',testPayload='';
 testForm.onsubmit=async event=>{event.preventDefault();testButton.disabled=true;const body={items:[{id:'corazon-007',variant:1,quantity:1}],customer:{name:'Comprador de prueba ODA',email:testEmail.value.trim(),method:'pickup'}};const encoded=JSON.stringify(body);if(encoded!==testPayload){testPayload=encoded;testKey=crypto.randomUUID();}try{const r=await fetch(base+'/api/admin/test-checkout',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','Idempotency-Key':testKey},body:encoded});const data=await r.json();if(!r.ok)throw Error(data.error);const u=new URL(data.checkout_url);if(u.protocol!=='https:'||!['www.mercadopago.com.mx','sandbox.mercadopago.com.mx'].includes(u.hostname))throw Error('Enlace no válido.');testResult.replaceChildren();const link=el('a','Abrir Mercado Pago para completar la prueba');link.href=u.href;link.target='_blank';link.rel='noopener noreferrer';testResult.append(link,el('p','Pedido: '+data.order_id));say('Pedido de prueba preparado. Ábrelo e inicia sesión como comprador de prueba.');}catch(e){say(e.message)}finally{testButton.disabled=false}};
 function showLabels(r,target){for(const label of r.labels||[]){let url;try{url=new URL(label.label_url)}catch{continue}if(url.protocol!=='https:')continue;const a=el('a','Descargar guía PDF ? '+label.tracking);a.href=url.href;a.target='_blank';a.rel='noopener noreferrer';target.append(el('p',label.carrier),a)}if(r.cost_warning)say('La paquetería report? un importe superior al cotizado. Revisa el cargo en Envia.com.');}
 async function load(){const g=generation;const [s,o]=await Promise.all([api('status'),api('orders')]);if(g!==generation)return;
 $('connections').textContent=`Mercado Pago: modo ${s.mode==='live'?'real':'prueba'} · Cobros ${s.payments_enabled?'habilitados':'desactivados'} · Envia.com ${s.envia_connected?'credencial guardada (pendiente de prueba)':'pendiente de conectar'}.`;
 if(s.origin)for(const [k,v] of Object.entries(s.origin)){const input=$('origin').elements.namedItem(k);if(input)input.value=v;}
 $('inventory').replaceChildren();for(const item of s.inventory){const f=el('form');f.className='item';f.append(el('h3',item.title));const grid=el('div');grid.className='grid';
 for(const [key,label] of [['stock','Unidades disponibles'],['weight','Peso (kg)'],['length','Largo (cm)'],['width','Ancho (cm)'],['height','Alto (cm)']]){const l=el('label',label),i=el('input');i.name=key;i.type='number';i.required=true;i.min=key==='stock'?'0':'0.01';i.max=key==='stock'?'10000':key==='weight'?'100':'300';i.step=key==='stock'?'1':'0.01';i.value=item[key]??'';l.append(i);grid.append(l)}f.append(grid);const b=el('button','Guardar existencias y paquete');f.append(b);f.onsubmit=async e=>{e.preventDefault();b.disabled=true;try{const data={product_id:item.product_id,variant:item.variant,previous_stock:item.stock};for(const [k,v] of new FormData(f))data[k]=Number(v);await api('inventory',data);await load();say('Existencias y paquete guardados.')}catch(e){say(e.message)}finally{b.disabled=false}};$('inventory').append(f)}
 $('orders').replaceChildren();if(!o.orders.length)$('orders').append(el('p','Todavía no hay pedidos registrados.'));for(const x of o.orders){const d=el('article');d.className='order';d.append(el('h3',x.id),el('p',`${x.state} · ${x.mode==='test'?'PRUEBA':'VENTA REAL'} · ${new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(x.total_cents/100)}`),el('p',`${x.customer.name} · ${x.customer.email}`),el('p',x.items.map(i=>`${i.quantity} × ${i.title}`).join(' / ')));d.append(el('p',`Piezas: $${((x.total_cents-x.shipping_cents)/100).toFixed(2)} MXN / Envío: $${(x.shipping_cents/100).toFixed(2)} MXN`));const checkPayment=el('button','Actualizar pago');d.append(checkPayment);checkPayment.onclick=async()=>{checkPayment.disabled=true;try{const p=await api('orders/'+x.id+'/payment',{});say('Estado del pago: '+p.status);await load()}catch(e){say(e.message);checkPayment.disabled=false}};if(x.state==='approved'&&x.customer.method==='shipping'){
 const b=el('button','Consultar guía y precio');d.append(b);b.onclick=async()=>{b.disabled=true;try{const r=await api('orders/'+x.id+'/rate',{});if(r.state==='ready'){showLabels(r,d);return;}const buy=el('button',`Comprar guía por $${r.total.toFixed(2)} MXN`);d.append(el('p',r.description+' / '+r.estimate),buy);buy.onclick=async()=>{if(!confirm(`Comprar esta guía por $${r.total.toFixed(2)} MXN con tu saldo de Envia.com? La paquetería puede aplicar ajustes por peso o medidas incorrectas.`))return;buy.disabled=true;try{const result=await api('orders/'+x.id+'/label',{expected_cents:r.total_cents});showLabels(result,d);say('Guía generada. Descarga el PDF para imprimir.')}catch(e){say(e.message)}}}catch(e){say(e.message);b.disabled=false}};
 }$('orders').append(d)}
 $('panel').hidden=false;$('login').hidden=true;$('logout').hidden=false;
 }
 $('login').onsubmit=async e=>{e.preventDefault();token=$('key').value;$('key').value='';say('Abriendo panel…');try{await load();say('Panel conectado.')}catch(e){token='';say(e.message)}};
 $('logout').onclick=()=>{generation++;token='';$('panel').hidden=true;$('panel').querySelectorAll('input').forEach(i=>i.value='');$('inventory').replaceChildren();$('orders').replaceChildren();$('login').hidden=false;$('logout').hidden=true;say('Sesión cerrada.')};
 $('origin').onsubmit=async e=>{e.preventDefault();try{await api('origin',Object.fromEntries(new FormData(e.currentTarget)));say('Origen privado guardado.')}catch(e){say(e.message)}};
 $('refresh').onclick=async()=>{try{await load();say('Datos actualizados.')}catch(e){say(e.message)}};
 const shippingCheck=el('button','Comprobar Envia.com (prueba)');$('verify').after(shippingCheck);shippingCheck.onclick=async()=>{shippingCheck.disabled=true;try{const r=await api('envia-test',{});say('Envia.com respondi?. Servicios: '+r.services+'. '+r.note)}catch(e){say(e.message)}finally{shippingCheck.disabled=false}};
 $('verify').onclick=async()=>{say('Consultando Mercado Pago…');try{const d=await api('mercadopago',{});say((d.collector_matches?'Credencial válida y vendedor coincidente. ':'La credencial funciona, pero el vendedor no coincide con MP_COLLECTOR_ID. ')+d.message)}catch(e){say(e.message)}};
})();
