'use strict';
window.createContentManager=function(api,say,reloadInventory){
 const root=document.getElementById('contentManager');let data=null,editing=false;
 const make=(tag,txt,cls)=>{const n=document.createElement(tag);if(txt!==undefined)n.textContent=txt;if(cls)n.className=cls;return n};
 const sections=[['products','Piezas'],['canvases','Lienzos'],['collections','Colecciones'],['promotions','Promociones']];let selected='products';
 const toolbar=make('div',undefined,'content-toolbar'),tabs=make('div',undefined,'admin-tabs'),search=make('input');search.type='search';search.placeholder='Buscar por nombre…';search.setAttribute('aria-label','Buscar en el catálogo');
 const add=make('button','+ Agregar pieza'),list=make('div',undefined,'content-list'),editor=make('dialog');editor.className='content-editor';editor.setAttribute('aria-label','Editor del catálogo');root.append(toolbar,list,editor);toolbar.append(tabs,search,add);
 for(const [key,title]of sections){const b=make('button',title);b.onclick=()=>{selected=key;render()};b.dataset.section=key;tabs.append(b)}
 const productSection=()=>selected==='products'||selected==='canvases';const storageKey=()=>productSection()?'products':selected;
 search.oninput=()=>render();add.onclick=()=>edit(null);
 async function load(){data=await api('content');render();}
 function render(){if(!data)return;tabs.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.section===selected));add.textContent='+ Agregar '+({products:'pieza',canvases:'lienzo',collections:'colección',promotions:'promoción'}[selected]);list.replaceChildren();
 const rows=data[storageKey()].filter(x=>(!productSection()||(selected==='canvases'?x.category==='lienzo':x.category!=='lienzo'))).filter(x=>(x.name||x.title).toLocaleLowerCase().includes(search.value.toLocaleLowerCase()));
 if(!rows.length)list.append(make('p','Aquí empieza tu próxima colección. Agrega tu primer elemento.','empty-admin'));
 for(const x of rows){const row=make('article',undefined,'content-row');if(x.image){const img=make('img');img.src=/^(https:|data:)/.test(x.image)?x.image:'assets/images/'+x.image;img.alt=x.name;row.append(img)}const info=make('div');info.append(make('h3',x.name||x.title));const state=x.active===false?'Oculto':selected==='promotions'?(!x.active?'Pausada':x.start&&Date.parse(x.start)>Date.now()?'Programada':x.end&&Date.parse(x.end)<=Date.now()?'Finalizada':'Activa'):'Publicado';info.append(make('p',productSection()?(x.price===null?'Por cotización':'$'+x.price.toFixed(2)+' MXN')+' · '+state:selected==='promotions'?x.percent+'% · '+state:state));row.append(info);const button=make('button','Editar');button.onclick=()=>edit(x);row.append(button);list.append(row)}
 }
 function edit(existing){editing=true;editor.replaceChildren();const title=make('h2',existing?'Editar '+(existing.name||existing.title):selected==='canvases'?'Nuevo lienzo':selected==='products'?'Nueva pieza':'Nuevo elemento'),form=make('form'),grid=make('div',undefined,'editor-grid'),buttons=make('div',undefined,'editor-actions'),close=make('button','Cancelar'),submit=make('button','Guardar y publicar'),status=make('p');status.setAttribute('role','status');close.type='button';close.onclick=()=>editor.close();editor.oncancel=()=>{editing=false};editor.onclose=()=>{editing=false;add.focus()};submit.type='submit';editor.append(title,form);form.append(grid,status,buttons);buttons.append(close,submit);const values={};const x=existing||{};
 function field(key,label,type='text',value='',opts){const l=make('label',label);const input=make(type==='textarea'?'textarea':type==='select'?'select':'input');if(type==='select')for(const [v,t]of opts){const o=make('option',t);o.value=v;input.append(o)}else if(type!=='textarea')input.type=type;if(type==='checkbox')input.checked=!!value;else input.value=value??'';input.name=key;values[key]=input;l.append(input);grid.append(l);return input;}
 const name=field(selected==='promotions'?'title':'name',selected==='promotions'?'Título de la promoción':'Nombre','text',x.name||x.title||'');name.required=true;name.maxLength=100;
 field('active',selected==='promotions'?'Activar promoción':'Visible en la tienda','checkbox',x.active!==false);
 if(selected!=='promotions'){
 field('description','Descripción','textarea',x.description||'').maxLength=1500;
 const preview=make('img');preview.className='upload-preview';let images=[x.image||'',...(x.images||[])];const imageURL=field('image','Foto principal (URL HTTPS o archivo existente)','text',x.image?.startsWith('data:')?'':x.image||'');imageURL.required=!images[0];imageURL.oninput=()=>{images[0]=imageURL.value;preview.src=/^(https:|data:)/.test(images[0])?images[0]:'assets/images/'+images[0]};if(images[0])preview.src=/^(https:|data:)/.test(images[0])?images[0]:'assets/images/'+images[0];
 const upload=field('upload',productSection()?'Subir fotos (primera = portada, hasta 5)':'Subir portada','file');upload.accept='image/jpeg,image/png,image/webp';upload.multiple=productSection();grid.append(preview);const note=make('p','Las fotos se optimizan al subirlas. Elegir fotos reemplaza las anteriores.');grid.append(note);
 upload.onchange=async()=>{submit.disabled=true;status.textContent='Optimizando fotos…';try{if(upload.files.length>(productSection()?5:1))throw Error('Selecciona menos fotos.');const result=[];for(const file of upload.files){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15000000)throw Error('Usa JPG, PNG o WebP de hasta 15 MB.');const bitmap=await createImageBitmap(file);const canvas=document.createElement('canvas'),scale=Math.min(1,900/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();let quality=.8,encoded;do{encoded=canvas.toDataURL('image/webp',quality);quality-=.1}while(encoded.length>185000&&quality>.1);if(encoded.length>185000)throw Error('Esta foto tiene demasiado detalle. Prueba una imagen más pequeña.');result.push(encoded)}if(result.length){images=result;imageURL.value='';imageURL.required=false;preview.src=images[0]}status.textContent='Fotos listas para guardar.';}catch(e){status.textContent=e.message}finally{submit.disabled=false}};
 values.getImages=()=>images;
 }
 if(productSection()){
 field('category','Categoría','select',selected==='canvases'?'lienzo':x.category||'art-toy',selected==='canvases'?[['lienzo','Lienzos']]:[['art-toy','Figuras de diseño'],['figura','Figuras'],['custom','Personalizados']]);field('type','Forma de venta','select',x.type||'fixed',[['fixed','Precio fijo'],['custom','Por cotización']]);const price=field('price','Precio base (MXN)','number',x.price??0);price.min=1;price.max=1000000;price.step='.01';
 field('collection','Colección','select',x.collection||'',[['','Sin colección'],...data.collections.map(c=>[c.id,c.name])]);field('featured','Destacar en catálogo','checkbox',x.featured);
 const variants=field('variants',selected==='canvases'?'Tamaños y acabados: uno por línea, nombre | precio adicional':'Acabados: uno por línea, nombre | precio adicional','textarea',(x.variants||[{name:'Estándar',mod:0}]).map(v=>v.name+' | '+v.mod).join('\n'));grid.append(make('p','Conserva el orden de los acabados existentes: las existencias se identifican por su posición. Las piezas nuevas empiezan con existencias en cero; configúralo en Existencias.'));
 const update=()=>{price.disabled=values.type.value==='custom';price.required=!price.disabled;variants.required=!price.disabled};values.type.onchange=update;update();
 }
 if(selected==='promotions'){
 const percent=field('percent','Descuento (%)','number',x.percent||10);percent.min=1;percent.max=90;percent.step='.01';percent.required=true;field('collection','Aplicar a','select',x.collection||'',[['','Todo el catálogo'],...data.collections.map(c=>[c.id,c.name])]);
 const local=s=>s?new Date(Date.parse(s)-new Date(s).getTimezoneOffset()*60000).toISOString().slice(0,16):'';field('start','Comienza (hora de tu dispositivo)','datetime-local',local(x.start));field('end','Termina (opcional)','datetime-local',local(x.end));grid.append(make('p','Se activa y termina automáticamente por fecha. Si coinciden promociones, se aplica solo el mayor descuento, también a los acabados.'));
 }
 form.onsubmit=async e=>{e.preventDefault();submit.disabled=true;status.textContent='Guardando…';try{const item={...x,id:x.id||selected.slice(0,3)+'-'+crypto.randomUUID(),active:values.active.checked};for(const k of ['name','title','description','category','type','collection'])if(values[k])item[k]=values[k].value.trim();if(values.getImages){const imgs=values.getImages();item.image=imgs[0];item.images=imgs.slice(1)}if(productSection()){item.price=item.type==='custom'?null:Number(values.price.value);item.featured=values.featured.checked;item.variants=item.type==='custom'?[]:values.variants.value.split('\n').filter(Boolean).map(line=>{const pos=line.lastIndexOf('|');if(pos<1)throw Error('Escribe cada acabado como Nombre | 0');return {name:line.slice(0,pos).trim(),mod:Number(line.slice(pos+1).trim())}})}if(selected==='promotions'){item.percent=Number(values.percent.value);for(const k of ['start','end'])item[k]=values[k].value?new Date(values[k].value).toISOString():'';}
 const next=structuredClone(data);const index=next[storageKey()].findIndex(a=>a.id===item.id);if(index<0)next[storageKey()].push(item);else next[storageKey()][index]=item;data=await api('content',next);editor.close();render();say('Cambios publicados. La tienda los mostrará al recargar.');reloadInventory().catch(()=>say('Catálogo guardado. Actualiza existencias para ver las piezas nuevas.'));}catch(e){status.textContent=e.message}finally{submit.disabled=false}};
 editor.showModal();name.focus();
 }
 return {load,clear(){data=null;list.replaceChildren();editor.close();}};
};
