 'use strict';
// Propuestas comerciales editables. Se solicitan por cotización, no se aplican al carrito.
const ODA_PROMOS=[
 {id:'VENOM20',title:'MÁS CARÁCTER. MENOS PRECIO.',badge:'−20%',image:'ven1.png',alt:'Figura Venom',description:'Figura Venom sin pintar.',regular:850,price:680,terms:'Una figura sin pintar. Pintura y envío se cotizan por separado.'},
 {id:'DUO599',title:'DOS PIEZAS. UN MISMO SPOT.',badge:'AHORRA $131',image:'cat-sit.png',alt:'Gato Sentado del combo',description:'Combo Gato Sentado + Conejo Decorativo, ambos sin pintar.',regular:730,price:599,terms:'Incluye una figura de cada modelo, sin pintar. Envío por separado.'},
 {id:'LIENZOREGALO',title:'ARTE EN TU PARED. REGALO EN TU SPOT.',badge:'FIGURA DE REGALO',image:'cat-sit.png',alt:'Gato Sentado de regalo con tu lienzo',description:'Al cotizar un lienzo de $1,800 MXN o más, incluye un Gato Sentado sin pintar de regalo.',price:null,terms:'Un regalo por lienzo elegible. El precio del lienzo depende de medidas y diseño; envío por separado.'},
 {id:'CORAZON15',title:'UNA PIEZA CON CORAZÓN.',badge:'−15%',image:'corazon1.png',alt:'Corazón Anatómico 3D',description:'Corazón Anatómico 3D sin pintar.',regular:550,price:467.5,terms:'Una figura sin pintar. Pintura y envío se cotizan por separado.'}
];
if(page==='index'||page==='tienda'){
 const promoMoney=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',minimumFractionDigits:Number.isInteger(n)?0:2}).format(n);
 const mxDate=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Mexico_City',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const parts=mxDate.split('-').map(Number);const today=Date.UTC(parts[0],parts[1]-1,parts[2]);
 const week=Math.floor((today-Date.UTC(2026,9,5))/(7*86400000));
 const first=((week%ODA_PROMOS.length)+ODA_PROMOS.length)%ODA_PROMOS.length;
 const offers=ODA_PROMOS.map((_,i)=>ODA_PROMOS[(i+first)%ODA_PROMOS.length]);
 const section=document.createElement('section');section.className='wrap weekly-promos';section.id='promociones';section.setAttribute('aria-labelledby','promoHeading');
 section.innerHTML=`<div class="section-head"><div><span class="eyebrow">ODA OFFERS / DALE OTRO LOOK A TU SPOT</span><h2 id="promoHeading">PROMOCIÓN<br>DE LA <span>SEMANA.</span></h2></div><p class="promo-intro">Una selección que cambia cada semana. Explora las ofertas y solicita la que más va contigo.</p></div><div class="promo-stage">${offers.map((p,i)=>`<article class="promo-slide" ${i?'hidden':''} aria-label="Oferta ${i+1} de ${offers.length}"><div class="promo-art"><span class="promo-badge">${p.badge}</span><img src="assets/images/${p.image}" alt="${p.alt}" loading="lazy"><span class="promo-code">ODA / ${p.id}</span></div><div class="promo-copy"><span class="eyebrow">${i===0?'DESTACADA DE ESTA SEMANA':'MÁS OFERTAS DEL ESTUDIO'}</span><h3>${p.title}</h3><p>${p.description}</p><div class="promo-price">${p.price!==null?`<span class="promo-regular">Precio de catálogo ${promoMoney(p.regular)}</span><strong>${promoMoney(p.price)} <small>MXN</small></strong>`:'<strong class="promo-gift">TU LIENZO + TU REGALO</strong>'}</div><a class="btn lime" href="https://wa.me/524492795557?text=${encodeURIComponent('Hola ODA Studio, quiero solicitar la promoción '+p.id+': '+p.description+(p.price!==null?' Precio promocional: '+promoMoney(p.price)+' MXN.':'')+' ¿Me confirman disponibilidad, total con envío y tiempo de entrega?')}" target="_blank" rel="noopener noreferrer">SOLICITAR PROMOCIÓN ↗</a><p class="promo-terms">${p.terms}</p></div></article>`).join('')}</div><div class="promo-controls"><div class="promo-dots" role="group" aria-label="Elegir promoción">${offers.map((p,i)=>`<button type="button" data-promo="${i}" aria-label="Ver promoción ${p.id}" aria-pressed="${i===0}">${i+1}</button>`).join('')}</div><button type="button" class="promo-pause">Pausar rotación</button></div><p class="promo-fineprint">Promociones por cotización. Sujetas a disponibilidad y confirmación del estudio; no acumulables. Solicítalas por WhatsApp: los descuentos y regalos no se agregan automáticamente al carrito.</p>`;
 const anchor=page==='index'?document.querySelector('main > .wrap'):document.querySelector('#lienzos');anchor.before(section);
 let active=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)');let paused=reduced.matches;
 const pause=section.querySelector('.promo-pause');const refreshPause=()=>{pause.textContent=paused?'Reanudar rotación':'Pausar rotación';pause.setAttribute('aria-pressed',String(paused))};refreshPause();
 const show=i=>{active=i;section.querySelectorAll('.promo-slide').forEach((el,n)=>el.hidden=n!==i);section.querySelectorAll('[data-promo]').forEach((el,n)=>el.setAttribute('aria-pressed',String(n===i)))};
 section.querySelectorAll('[data-promo]').forEach(b=>b.onclick=()=>{show(Number(b.dataset.promo));paused=true;refreshPause()});pause.onclick=()=>{paused=!paused;refreshPause()};
 reduced.addEventListener('change',e=>{paused=e.matches;refreshPause()});
 setInterval(()=>{if(!paused&&!document.hidden&&!section.matches(':hover')&&!section.contains(document.activeElement))show((active+1)%offers.length)},7000);
}
