import SEED from './catalog-seed.mjs';
import {APIError} from './errors.mjs';
const q=(e,s,...v)=>e.DB.prepare(s).bind(...v);
export async function getContent(e){const r=await q(e,"SELECT value FROM store_settings WHERE key='content'").first();return r?JSON.parse(r.value):{revision:0,products:SEED,collections:[],promotions:[]};}
export function activePromotions(c,time=Date.now()){return c.promotions.filter(x=>x.active&&(!x.start||Date.parse(x.start)<=time)&&(!x.end||Date.parse(x.end)>time));}
export function pricedProducts(c,time=Date.now()){const offers=activePromotions(c,time);return c.products.filter(p=>p.active!==false).map(p=>{const promo=offers.filter(x=>!x.collection||p.collection===x.collection).sort((a,b)=>b.percent-a.percent)[0];const rate=1-(promo?.percent||0)/100;return {...p,originalPrice:p.price,price:p.price===null?null:Math.round(p.price*rate*100)/100,variants:p.variants.map(v=>({...v,mod:Math.round(v.mod*rate*100)/100})),promotion:promo?.title||''};});}
const bad=m=>{throw new APIError(400,m)};
function text(x,max=200){if(typeof x!=='string'||x.length>max||/[<>]/.test(x))bad('Revisa los textos: no se admite HTML.');return x.trim();}
function image(x){if(typeof x!=='string'||x.length>190000||!(/^[a-zA-Z0-9_.-]+$/.test(x)||/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(x)||/^https:\/\/[^\s"'<>]+$/.test(x)))bad('Imagen no válida. Usa JPG, PNG, WebP o una URL HTTPS.');return x;}
export function validateContent(b){
 if(!b||!Number.isInteger(b.revision)||!Array.isArray(b.products)||!Array.isArray(b.collections)||!Array.isArray(b.promotions)||b.products.length>100||b.collections.length>40||b.promotions.length>40)bad('Contenido no válido o demasiado grande.');
 const ids=new Set();const id=x=>{if(typeof x!=='string'||!/^[-a-z0-9]{1,60}$/.test(x)||ids.has(x))bad('Identificador repetido o no válido.');ids.add(x);return x};
 const collections=b.collections.map(x=>({id:id(x.id),name:text(x.name,80),description:text(x.description||'',400),image:image(x.image),active:!!x.active}));
 const products=b.products.map(x=>{if(!['fixed','custom'].includes(x.type)||!['art-toy','figura','custom'].includes(x.category)||!Array.isArray(x.variants)||x.variants.length>8||x.type==='fixed'&&(!Number.isFinite(x.price)||x.price<1||x.price>1000000||!x.variants.length))bad('Revisa el precio y los acabados.');if(x.collection&&!collections.some(c=>c.id===x.collection))bad('Colección no encontrada.');return {id:id(x.id),name:text(x.name,100),description:text(x.description||'',1500),category:x.category,type:x.type,price:x.type==='custom'?null:x.price,variants:x.variants.map(v=>{if(!Number.isFinite(v.mod)||v.mod<0||v.mod>1000000)bad('Precio adicional no válido.');return {name:text(v.name,80),mod:v.mod}}),image:image(x.image),images:(x.images||[]).slice(0,4).map(image),tags:[],featured:!!x.featured,active:x.active!==false,collection:x.collection||''};});
 const promotions=b.promotions.map(x=>{if(!Number.isFinite(x.percent)||x.percent<1||x.percent>90)bad('El descuento debe estar entre 1 y 90%.');if(x.collection&&!collections.some(c=>c.id===x.collection))bad('Colección de promoción no encontrada.');for(const k of ['start','end'])if(x[k]&&!Number.isFinite(Date.parse(x[k])))bad('Fecha no válida.');if(x.start&&x.end&&Date.parse(x.end)<=Date.parse(x.start))bad('El fin debe ser posterior al inicio.');return {id:id(x.id),title:text(x.title,100),percent:x.percent,collection:x.collection||'',start:x.start||'',end:x.end||'',active:!!x.active};});
 const result={revision:b.revision+1,products,collections,promotions};if(JSON.stringify(result).length>1800000)bad('El catálogo supera 1.8 MB. Reduce el número o tamaño de las fotos.');return result;
}
export async function saveContent(e,body){const next=validateContent(body);await q(e,"INSERT OR IGNORE INTO store_settings(key,value) VALUES('content',?)",JSON.stringify({revision:0,products:SEED,collections:[],promotions:[]})).run();const old=await getContent(e);if(old.revision!==body.revision)throw new APIError(409,'Otra sesión modificó el catálogo. Recarga antes de guardar.');
 const commands=[q(e,"UPDATE store_settings SET value=? WHERE key='content' AND value=?",JSON.stringify(next),JSON.stringify(old))];
 for(const p of next.products)for(let i=0;i<p.variants.length;i++)commands.push(q(e,'INSERT OR IGNORE INTO inventory(product_id,variant,stock) VALUES(?,?,0)',p.id,i));
 const result=await e.DB.batch(commands);if(result[0].meta.changes!==1)throw new APIError(409,'El catálogo cambió. Recarga el panel.');return next;}
